using System;
using System.Collections.Generic;
using System.Text;

namespace Voicecoin.RestApi
{
    public class TwilioCallbackModel
    {
        //The unique 34 character ID of the transcription.
        public string TranscriptionSid { get; set; }
        //Contains the text of the transcription.
        public string TranscriptionText { get; set; }
        //The status of the transcription attempt: either 'completed' or 'failed'.
        public string TranscriptionStatus { get; set; }
        //The URL for the transcription's REST API resource.
        public string TranscriptionUrl { get; set; }
        //The unique 34 character ID of the recording from which the transcription was generated.
        public string RecordingSid { get; set; }
        //The URL for the transcription's source recording resource.
        public string RecordingUrl { get; set; }
        //A unique identifier for this call, generated by Twilio.
        public string CallSid { get; set; }
        //Your Twilio account id. It is 34 characters long, and always starts with the letters AC.
        public string AccountSid { get; set; }
        //FrommPhone Number
        public string From { get; set; }
        // To Phone Number
        public string To { get; set; }
        //A descriptive status for the call. The value is one of queued, ringing, in-progress, completed, busy, failed or no-answer.
        public string CallStatus { get; set; }
        public string ApiVersion { get; set; }
        public string Direction { get; set; }
        //This parameter is set only when Twilio receives a forwarded call, 
        //but its value depends on the caller's carrier including information when forwarding. 
        //Not all carriers support passing this information.
        public string ForwardedFrom { get; set; }

        public string SpeechResult { get; set; }
        public string Confidence { get; set; }
    }
}
